service: {{name}}

custom:
  cljsCompiler: lumo

provider:
  name: aws
  runtime: nodejs6.10

functions:
  get:
    cljs: {{name}}.core/get
    events:
      - http:
          path: get
          method: get
          cors: true

package:
  exclude:
    - node_modules/.yarn*
    - src/**
    - README.md

plugins:
  - serverless-cljs-plugin
